package m.Scanner;

public enum TokenType {

    LEFT_BRACKET, RIGHT_BRACKET, LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, HASH,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, COLON, SLASH, STAR, POWER,

    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,


    IDENTIFIER, STRING, NUMBER,


    AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NODEF, OR,
    PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE,


    FN, INVALID_TOKEN, EOF
}
