public enum TokenKind {
    // Logical
    DOUBLE_AND,
    DOUBLE_PIPE,
    BANG,
    PIPE,
    LEFT_ARROW,
    RIGHT_ARROW,
    EQUALS,
    DOUBLE_EQUALS,
    LEFT_ARROW_EQUALS,
    RIGHT_ARROW_EQUALS,
    BANG_EQUALS,
    // Mathematics
    STAR,
    PLUS,
    SLASH,
    DOUBLE_SLASH,
    // Keywords
    WHILE,
    FOR,
    IF,
    ELSE,
    ALIAS,
    NAMESPACE,
    INCLUDES,
    // Other..
    NUMERAL,
    LEFT_BRACKET,
    RIGHT_BRACKET,
    LEFT_PAREN,
    RIGHT_PAREN,
    COLON,
    DOUBLE_QUOTE,
    HASH,
    COMMA,
    END_OF_FILE,
    INVALID_TOKEN,
}
